version: '3.8'

services:
    sttangbucks-mysql:
        image: mysql:8.0
        container_name: sttangbucks-mysql
        ports:
            - '${MYSQL_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
            TZ: Asia/Seoul
        volumes:
            - mysql_data:/var/lib/mysql
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
            - --default-time-zone=+09:00

volumes:
    mysql_data:
